return {
    ["warning"]=false, 
    ["layout"]={
        ["draggable"]=false, 
        ["padding"]=3, 
        ["font"]={
            ["name"]="Lucida Console", 
            ["size"]=8
        }, 
        ["colors"]={
            ["text"]={
                ["r"]=245, 
                ["alpha"]=255, 
                ["g"]=200, 
                ["b"]=20
            }, 
            ["bg"]={
                ["r"]=0, 
                ["alpha"]=200, 
                ["g"]=0, 
                ["b"]=0
            }, 
            ["stroke"]={
                ["r"]=0, 
                ["alpha"]=255, 
                ["g"]=0, 
                ["b"]=0
            }
        }, 
        ["stroke_width"]=1, 
        ["pos"]={
            ["y"]=400, 
            ["x"]=500
        }
    }, 
    ["position"]=1
}