return {
    ["layout"]={
        ["draggable"]=false, 
        ["padding"]=2, 
        ["stroke_width"]=2, 
        ["colors"]={
            ["text"]={
                ["b"]=0, 
                ["alpha"]=255, 
                ["g"]=215, 
                ["r"]=100
            }, 
            ["bg"]={
                ["b"]=0, 
                ["alpha"]=0, 
                ["g"]=0, 
                ["r"]=0
            }, 
            ["stroke"]={
                ["b"]=15, 
                ["alpha"]=255, 
                ["g"]=25, 
                ["r"]=0
            }
        }, 
        ["font"]={
            ["name"]="Mulish", 
            ["size"]=8
        }, 
        ["pos"]={
            ["y"]=400, 
            ["x"]=300
        }
    }
}