return {
    ["stuns"]={}, 
    ["layout"]={
        ["draggable"]=false, 
        ["padding"]=8, 
        ["stroke_width"]=2, 
        ["colors"]={
            ["text"]={
                ["b"]=20, 
                ["alpha"]=255, 
                ["g"]=200, 
                ["r"]=245
            }, 
            ["bg"]={
                ["b"]=0, 
                ["alpha"]=200, 
                ["g"]=0, 
                ["r"]=0
            }, 
            ["stroke"]={
                ["b"]=20, 
                ["alpha"]=255, 
                ["g"]=80, 
                ["r"]=150
            }
        }, 
        ["font"]={
            ["name"]="Arial", 
            ["size"]=8
        }, 
        ["pos"]={
            ["y"]=0, 
            ["x"]=0
        }
    }
}