return {
    ["stuns"]={
        [2020]={
            ["id"]=2020, 
            ["ja"]="百烈拳", 
            ["en"]="Hundred Fists"
        }, 
        [3026]={
            ["id"]=3026, 
            ["ja"]="インシネレイトラハール", 
            ["en"]="Incinerating Lahar"
        }
    }, 
    ["layout"]={
        ["draggable"]=false, 
        ["padding"]=8, 
        ["font"]={
            ["name"]="Arial", 
            ["size"]=8
        }, 
        ["colors"]={
            ["text"]={
                ["r"]=245, 
                ["alpha"]=255, 
                ["g"]=220, 
                ["b"]=20
            }, 
            ["bg"]={
                ["r"]=0, 
                ["alpha"]=200, 
                ["g"]=0, 
                ["b"]=0
            }, 
            ["stroke"]={
                ["r"]=150, 
                ["alpha"]=255, 
                ["g"]=75, 
                ["b"]=60
            }
        }, 
        ["stroke_width"]=2, 
        ["pos"]={
            ["y"]=0, 
            ["x"]=0
        }
    }
}