return {
    ["runes"]={
        [1]={
            ["ja"]="テネブレイ", 
            ["prefix"]="/jobability", 
            ["icon_id"]=47, 
            ["range"]=0, 
            ["status"]=530, 
            ["tp_cost"]=0, 
            ["en"]="Tenebrae", 
            ["type"]="Rune", 
            ["targets"]={}, 
            ["recast_id"]=10, 
            ["element"]=7, 
            ["id"]=365, 
            ["duration"]=300, 
            ["mp_cost"]=1
        }, 
        [2]={
            ["ja"]="テネブレイ", 
            ["prefix"]="/jobability", 
            ["icon_id"]=47, 
            ["range"]=0, 
            ["status"]=530, 
            ["tp_cost"]=0, 
            ["en"]="Tenebrae", 
            ["type"]="Rune", 
            ["targets"]={}, 
            ["recast_id"]=10, 
            ["element"]=7, 
            ["id"]=365, 
            ["duration"]=300, 
            ["mp_cost"]=1
        }, 
        [3]={
            ["ja"]="テネブレイ", 
            ["prefix"]="/jobability", 
            ["icon_id"]=47, 
            ["range"]=0, 
            ["status"]=530, 
            ["tp_cost"]=0, 
            ["en"]="Tenebrae", 
            ["type"]="Rune", 
            ["targets"]={}, 
            ["recast_id"]=10, 
            ["element"]=7, 
            ["id"]=365, 
            ["duration"]=300, 
            ["mp_cost"]=1
        }
    }, 
    ["mode"]=1, 
    ["layout"]={
        ["draggable"]=false, 
        ["padding"]=0, 
        ["font"]={
            ["name"]="Impact", 
            ["size"]=11
        }, 
        ["colors"]={
            ["text"]={
                ["r"]=245, 
                ["alpha"]=255, 
                ["g"]=200, 
                ["b"]=20
            }, 
            ["bg"]={
                ["r"]=0, 
                ["alpha"]=0, 
                ["g"]=0, 
                ["b"]=0
            }, 
            ["stroke"]={
                ["r"]=0, 
                ["alpha"]=255, 
                ["g"]=0, 
                ["b"]=0
            }
        }, 
        ["stroke_width"]=2, 
        ["pos"]={
            ["y"]=800, 
            ["x"]=900
        }
    }
}