return {
    ["bubbles"]={
        [1]={
            ["mp_cost"]=63, 
            ["type"]="Geomancy", 
            ["element"]=0, 
            ["icon_id_nq"]=0, 
            ["targets"]={
	Self
}, 
            ["en"]="Indi-STR", 
            ["status"]=542, 
            ["skill"]=44, 
            ["recast_id"]=772, 
            ["id"]=772, 
            ["ja"]="インデスト", 
            ["range"]=0, 
            ["requirements"]=0, 
            ["icon_id"]=-1, 
            ["levels"]={
                [21]=48
            }, 
            ["recast"]=12, 
            ["prefix"]="/magic", 
            ["cast_time"]=2
        }, 
        [2]={
            ["mp_cost"]=59, 
            ["type"]="Geomancy", 
            ["element"]=3, 
            ["icon_id_nq"]=3, 
            ["targets"]={
	Self
}, 
            ["en"]="Indi-Barrier", 
            ["status"]=550, 
            ["skill"]=44, 
            ["recast_id"]=780, 
            ["id"]=780, 
            ["ja"]="インデバリア", 
            ["range"]=0, 
            ["requirements"]=0, 
            ["icon_id"]=-1, 
            ["levels"]={
                [21]=28
            }, 
            ["recast"]=12, 
            ["prefix"]="/magic", 
            ["cast_time"]=2
        }, 
        [3]={
            ["mp_cost"]=294, 
            ["type"]="Geomancy", 
            ["element"]=2, 
            ["icon_id_nq"]=2, 
            ["targets"]={
	Enemy
}, 
            ["skill"]=44, 
            ["en"]="Geo-Frailty", 
            ["recast_id"]=818, 
            ["id"]=818, 
            ["ja"]="ジオフレイル", 
            ["range"]=12, 
            ["requirements"]=32, 
            ["icon_id"]=-1, 
            ["levels"]={
                [21]=80
            }, 
            ["recast"]=12, 
            ["prefix"]="/magic", 
            ["cast_time"]=2
        }
    }, 
    ["layout"]={
        ["draggable"]=true, 
        ["padding"]=3, 
        ["font"]={
            ["name"]="Lucida Console", 
            ["size"]=9
        }, 
        ["colors"]={
            ["text"]={
                ["r"]=245, 
                ["alpha"]=255, 
                ["g"]=200, 
                ["b"]=20
            }, 
            ["bg"]={
                ["r"]=0, 
                ["alpha"]=200, 
                ["g"]=0, 
                ["b"]=0
            }, 
            ["stroke"]={
                ["r"]=0, 
                ["alpha"]=255, 
                ["g"]=0, 
                ["b"]=0
            }
        }, 
        ["stroke_width"]=1, 
        ["pos"]={
            ["y"]=350, 
            ["x"]=500
        }
    }
}