return {
    ["mode"]=1, 
    ["layout"]={
        ["draggable"]=false, 
        ["padding"]=4, 
        ["stroke_width"]=2, 
        ["colors"]={
            ["text"]={
                ["b"]=20, 
                ["alpha"]=255, 
                ["g"]=200, 
                ["r"]=245
            }, 
            ["bg"]={
                ["b"]=0, 
                ["alpha"]=200, 
                ["g"]=0, 
                ["r"]=0
            }, 
            ["stroke"]={
                ["b"]=0, 
                ["alpha"]=200, 
                ["g"]=0, 
                ["r"]=0
            }
        }, 
        ["font"]={
            ["name"]="Mulish", 
            ["size"]=9
        }, 
        ["pos"]={
            ["y"]=800, 
            ["x"]=420
        }
    }
}