return {
    ["layout"]={
        ["draggable"]=false, 
        ["padding"]=2, 
        ["stroke_width"]=1, 
        ["colors"]={
            ["text"]={
                ["b"]=20, 
                ["alpha"]=255, 
                ["g"]=200, 
                ["r"]=245
            }, 
            ["bg"]={
                ["b"]=0, 
                ["alpha"]=200, 
                ["g"]=0, 
                ["r"]=0
            }, 
            ["stroke"]={
                ["b"]=0, 
                ["alpha"]=255, 
                ["g"]=0, 
                ["r"]=0
            }
        }, 
        ["font"]={
            ["name"]="Impact", 
            ["size"]=8
        }, 
        ["pos"]={
            ["y"]=500, 
            ["x"]=1000
        }
    }, 
    ["mode"]=1, 
    ["weights"]={}, 
    ["power"]=15
}