return {
    ["weights"]={}, 
    ["mode"]=1, 
    ["layout"]={
        ["draggable"]=false, 
        ["padding"]=5, 
        ["font"]={
            ["name"]="Lucida Console", 
            ["size"]=8
        }, 
        ["colors"]={
            ["text"]={
                ["r"]=245, 
                ["alpha"]=255, 
                ["g"]=200, 
                ["b"]=20
            }, 
            ["bg"]={
                ["r"]=0, 
                ["alpha"]=200, 
                ["g"]=0, 
                ["b"]=0
            }, 
            ["stroke"]={
                ["r"]=0, 
                ["alpha"]=255, 
                ["g"]=0, 
                ["b"]=0
            }
        }, 
        ["stroke_width"]=1, 
        ["pos"]={
            ["y"]=500, 
            ["x"]=1000
        }
    }
}