return {
    ["enabled"]=true, 
    ["important"]="25,165,200", 
    ["layout"]={
        ["draggable"]=true, 
        ["padding"]=5, 
        ["stroke_width"]=2, 
        ["colors"]={
            ["text"]={
                ["b"]=20, 
                ["alpha"]=255, 
                ["g"]=200, 
                ["r"]=245
            }, 
            ["bg"]={
                ["b"]=0, 
                ["alpha"]=0, 
                ["g"]=0, 
                ["r"]=0
            }, 
            ["stroke"]={
                ["b"]=0, 
                ["alpha"]=255, 
                ["g"]=0, 
                ["r"]=0
            }
        }, 
        ["font"]={
            ["name"]="Impact", 
            ["size"]=12
        }, 
        ["pos"]={
            ["y"]=15, 
            ["x"]=1539
        }
    }, 
    ["speed"]=65
}