return {
    ["debuffs"]={
        [10]={
            [1]={
                ["id"]=230, 
                ["name"]="Bio", 
                ["last"]=3496.571, 
                ["delay"]=180
            }, 
            [2]={
                ["id"]=843, 
                ["name"]="Frazzle", 
                ["last"]=5016.735, 
                ["delay"]=180
            }, 
            [3]={
                ["id"]=260, 
                ["name"]="Dispel", 
                ["last"]=5026.077, 
                ["delay"]=180
            }, 
            [4]={
                ["id"]=374, 
                ["name"]="Foe Requiem VII", 
                ["last"]=5075.349, 
                ["delay"]=180
            }
        }
    }, 
    ["update"]={
        ["delay"]=2, 
        ["last"]=41731.223
    }, 
    ["layout"]={
        ["draggable"]=false, 
        ["padding"]=2, 
        ["font"]={
            ["name"]="Krona One", 
            ["size"]=7
        }, 
        ["colors"]={
            ["text"]={
                ["r"]=100, 
                ["alpha"]=255, 
                ["g"]=215, 
                ["b"]=0
            }, 
            ["bg"]={
                ["r"]=0, 
                ["alpha"]=0, 
                ["g"]=0, 
                ["b"]=0
            }, 
            ["stroke"]={
                ["r"]=0, 
                ["alpha"]=255, 
                ["g"]=25, 
                ["b"]=15
            }
        }, 
        ["stroke_width"]=2, 
        ["pos"]={
            ["y"]=300, 
            ["x"]=300
        }
    }
}