return {
    ["debuffs"]={}, 
    ["update"]={
        ["delay"]=2, 
        ["last"]=0
    }, 
    ["layout"]={
        ["draggable"]=false, 
        ["padding"]=2, 
        ["font"]={
            ["name"]="Mulish", 
            ["size"]=8
        }, 
        ["colors"]={
            ["text"]={
                ["r"]=100, 
                ["alpha"]=255, 
                ["g"]=215, 
                ["b"]=0
            }, 
            ["bg"]={
                ["r"]=0, 
                ["alpha"]=0, 
                ["g"]=0, 
                ["b"]=0
            }, 
            ["stroke"]={
                ["r"]=0, 
                ["alpha"]=255, 
                ["g"]=25, 
                ["b"]=15
            }
        }, 
        ["stroke_width"]=2, 
        ["pos"]={
            ["y"]=400, 
            ["x"]=300
        }
    }
}