return {

    ['Enabled']                   = true,
    ['Ping Delay']                = 0.6,
    ['Main Character']            = 'Eliidyr',
    ['Characters']                = {
        'Eliidyr','Clapmycheeks','Lordpotato','Duhpeter','Peenaspump','Turtle','Mutant','Ninjar',
    },
    ['Controllers'] = {
        'Eliidyr','Clapmycheeks','Lordpotato','Duhpeter','Peenaspump','Turtle','Mutant','Ninjar',
        'Uwu','Mieren','Doomvtwo','Mingway','Sombermabari','Zeroexeffeff','Pawjobs','Xaniko','Khyal','Gianni','Minimimi','Deathsoul','Fivestarplayer','Emos','Twochainz','Thunderlips','Dimora','Kasshoku'
    },
    ['Models'] = {
        ['head']    = 0,
        ['body']    = 0,
        ['hands']   = 0,
        ['legs']    = 0,
        ['feet']    = 0,
    },
    ['Auto Join'] = {
        'Eliidyr','Clapmycheeks','Lordpotato','Duhpeter','Peenaspump','Turtle','Mutant','Ninjar',
        'Uwu','Mieren','Doomvtwo','Mingway','Sombermabari','Zeroexeffeff','Pawjobs','Xaniko','Khyal','Gianni','Minimimi','Deathsoul','Fivestarplayer',
        'Khyat','Emos','Ishnia','Twochainz','Thunderlips','Dimora','Uncas','Solvarr','Hydaelynz','Myahihze','Kasshoku'
    },

    ['helpers'] = {

        {name='aftermath',      status=true},
        {name='accolades',      status=true},
        {name='actions',        status=true},
        {name='assist',         status=true},
        {name='alias',          status=true},
        {name='autoload',       status=true},
        {name='bpsocket',       status=true},
        {name='bubbles',        status=true},
        {name='bits',           status=true},
        {name='burst',          status=true},
        {name='buffer',         status=true},
        {name='buffs',          status=true},
        {name='coms',           status=true},
        {name='commands',       status=true},
        {name='controls',       status=true},
        {name='console',        status=true},
        {name='ciphers',        status=true},
        {name='chests',         status=true},
        {name='cures',          status=true},
        {name='dax',            status=true},
        {name='debuffs',        status=true},
        {name='distance',       status=true},
        {name='empyrean',       status=true},
        {name='enmity',         status=true},
        {name='maintenance',    status=true},
        {name='maps',           status=true},
        {name='models',         status=true},
        {name='mount',          status=true},
        {name='menus',          status=true},
        {name='rolls',          status=true},
        {name='runes',          status=true},
        {name='songs',          status=true},
        {name='queue',          status=true},
        {name='inventory',      status=true},
        {name='idle',           status=true},
        {name='target',         status=true},
        {name='party',          status=true},
        {name='equipment',      status=true},
        {name='popchat',        status=true},
        {name='stunner',        status=true},
        {name='noknock',        status=true},        
        {name='keybinds',       status=true},
        {name='romans',         status=true},
        {name='layout',         status=true},
        {name='speed',          status=true},
        {name='stratagems',     status=true},
        {name='status',         status=true},
        {name='sounds',         status=true},
        {name='sparks',         status=true},
        {name='items',          status=true},
        {name='roe',            status=true},

    },

}
