return {
    ["Enabled"]=true, 
    ["Characters"]={
        [1]="Eliidyr", 
        [2]="Turtle", 
        [3]="Ninjar", 
        [4]="Mutant", 
        [5]="Duhpeter", 
        [6]="Lordpotato", 
        [7]="Stunzeed"
    }, 
    ["Main Character"]="Eliidyr", 
    ["helpers"]={
        [1]={
            ["name"]="rolls", 
            ["status"]=true
        }, 
        [2]={
            ["name"]="runes", 
            ["status"]=true
        }, 
        [3]={
            ["name"]="songs", 
            ["status"]=true
        }, 
        [4]={
            ["name"]="queue", 
            ["status"]=true
        }, 
        [5]={
            ["name"]="actions", 
            ["status"]=true
        }, 
        [6]={
            ["name"]="inventory", 
            ["status"]=true
        }, 
        [7]={
            ["name"]="target", 
            ["status"]=true
        }, 
        [8]={
            ["name"]="buffs", 
            ["status"]=true
        }, 
        [9]={
            ["name"]="party", 
            ["status"]=true
        }, 
        [10]={
            ["name"]="equipment", 
            ["status"]=true
        }, 
        [11]={
            ["name"]="popchat", 
            ["status"]=true
        }, 
        [12]={
            ["name"]="debuffs", 
            ["status"]=true
        }, 
        [13]={
            ["name"]="bubbles", 
            ["status"]=true
        }, 
        [14]={
            ["name"]="stunner", 
            ["status"]=true
        }, 
        [15]={
            ["name"]="noknock", 
            ["status"]=true
        }, 
        [16]={
            ["name"]="bits", 
            ["status"]=true
        }, 
        [17]={
            ["name"]="models", 
            ["status"]=true
        }, 
        [18]={
            ["name"]="distance", 
            ["status"]=true
        }, 
        [19]={
            ["name"]="cures", 
            ["status"]=true
        }, 
        [20]={
            ["name"]="commands", 
            ["status"]=true
        }, 
        [21]={
            ["name"]="keybinds", 
            ["status"]=true
        }, 
        [22]={
            ["name"]="controls", 
            ["status"]=true
        }, 
        [23]={
            ["name"]="autoload", 
            ["status"]=true
        }, 
        [24]={
            ["name"]="romans", 
            ["status"]=true
        }, 
        [25]={
            ["name"]="maintenance", 
            ["status"]=true
        }, 
        [26]={
            ["name"]="aftermath", 
            ["status"]=true
        }, 
        [27]={
            ["name"]="layout", 
            ["status"]=true
        }, 
        [28]={
            ["name"]="speed", 
            ["status"]=true
        }, 
        [29]={
            ["name"]="stratagems", 
            ["status"]=true
        }, 
        [30]={
            ["name"]="status", 
            ["status"]=true
        }, 
        [31]={
            ["name"]="alias", 
            ["status"]=true
        }, 
        [32]={
            ["name"]="burst", 
            ["status"]=true
        }, 
        [33]={
            ["name"]="sparks", 
            ["status"]=true
        }, 
        [34]={
            ["name"]="items", 
            ["status"]=true
        }
    }, 
    ["Addons"]={
        [1]=""
    }, 
    ["Ping Delay"]=0.6, 
    ["Auto Join"]={
        [1]="Eliidyr", 
        [2]="Turtle", 
        [3]="Ninjar", 
        [4]="Mutant", 
        [5]="Duhpeter", 
        [6]="Uwu", 
        [7]="Doomvtwo", 
        [8]="Zutangdupes", 
        [9]="Wutangdupes", 
        [10]="Gianni", 
        [11]="Minimimi", 
        [12]="Mingway", 
        [13]="Pawjobs", 
        [14]="Xcalibur", 
        [15]="Stunzeed"
    }, 
    ["Controllers"]={
        [1]="Eliidyr", 
        [2]="Turtle", 
        [3]="Ninjar", 
        [4]="Mutant", 
        [5]="Duhpeter", 
        [6]="Uwu", 
        [7]="Doomvtwo", 
        [8]="Zutangdupes", 
        [9]="Wutangdupes", 
        [10]="Minimimi", 
        [11]="Gianni", 
        [12]="Stunzeed", 
        [13]="Mingway", 
        [14]="Pawjobs"
    }
}