return {
    ["Enabled"]=true, 
    ["Characters"]={
        [1]="Eliidyr", 
        [2]="Turtle", 
        [3]="Ninjar", 
        [4]="Mutant", 
        [5]="Duhpeter", 
        [6]="Lordpotato"
    }, 
    ["Controllers"]={
        [1]="Eliidyr", 
        [2]="Turtle", 
        [3]="Ninjar", 
        [4]="Mutant", 
        [5]="Duhpeter", 
        [6]="Uwu", 
        [7]="Doomvtwo", 
        [8]="Zutangdupes", 
        [9]="Wutangdupes", 
        [10]="Minimimi"
    }, 
    ["helpers"]={
        [1]={
            ["name"]="rolls", 
            ["status"]=true
        }, 
        [2]={
            ["name"]="runes", 
            ["status"]=true
        }, 
        [3]={
            ["name"]="songs", 
            ["status"]=true
        }, 
        [4]={
            ["name"]="queue", 
            ["status"]=true
        }, 
        [5]={
            ["name"]="actions", 
            ["status"]=true
        }, 
        [6]={
            ["name"]="inventory", 
            ["status"]=true
        }, 
        [7]={
            ["name"]="target", 
            ["status"]=true
        }, 
        [8]={
            ["name"]="buffs", 
            ["status"]=true
        }, 
        [9]={
            ["name"]="party", 
            ["status"]=true
        }, 
        [10]={
            ["name"]="equipment", 
            ["status"]=true
        }, 
        [11]={
            ["name"]="popchat", 
            ["status"]=true
        }, 
        [12]={
            ["name"]="debuffs", 
            ["status"]=true
        }, 
        [13]={
            ["name"]="bubbles", 
            ["status"]=true
        }, 
        [14]={
            ["name"]="stunner", 
            ["status"]=true
        }, 
        [15]={
            ["name"]="noknock", 
            ["status"]=true
        }, 
        [16]={
            ["name"]="bits", 
            ["status"]=true
        }, 
        [17]={
            ["name"]="models", 
            ["status"]=true
        }
    }, 
    ["Addons"]={
        [1]=""
    }, 
    ["Ping Delay"]=0.6, 
    ["Auto Join"]={
        [1]="Eliidyr", 
        [2]="Turtle", 
        [3]="Ninjar", 
        [4]="Mutant", 
        [5]="Duhpeter", 
        [6]="Uwu", 
        [7]="Doomvtwo", 
        [8]="Zutangdupes", 
        [9]="Wutangdupes", 
        [10]="Gianni", 
        [11]="Minimimi"
    }, 
    ["Main Character"]="Eliidyr"
}