return {
    ["layout"]={
        ["draggable"]=false, 
        ["padding"]=8, 
        ["stroke_width"]=2, 
        ["colors"]={
            ["text"]={
                ["b"]=0, 
                ["alpha"]=255, 
                ["g"]=0, 
                ["r"]=0
            }, 
            ["bg"]={
                ["b"]=0, 
                ["alpha"]=255, 
                ["g"]=0, 
                ["r"]=0
            }, 
            ["stroke"]={
                ["b"]=0, 
                ["alpha"]=255, 
                ["g"]=0, 
                ["r"]=0
            }
        }, 
        ["font"]={
            ["name"]="Arial", 
            ["size"]=8
        }, 
        ["pos"]={
            ["y"]=0, 
            ["x"]=0
        }
    }, 
    ["rolls"]={
        [1]={
            ["ja"]="サムライロール", 
            ["prefix"]="/jobability", 
            ["tp_cost"]=0, 
            ["targets"]={
	Self
}, 
            ["status"]=321, 
            ["en"]="Samurai Roll", 
            ["recast_id"]=193, 
            ["type"]="CorsairRoll", 
            ["range"]=0, 
            ["icon_id"]=485, 
            ["element"]=1, 
            ["id"]=109, 
            ["duration"]=300, 
            ["mp_cost"]=0
        }, 
        [2]={
            ["ja"]="カオスロール", 
            ["prefix"]="/jobability", 
            ["tp_cost"]=0, 
            ["targets"]={
	Self
}, 
            ["status"]=317, 
            ["en"]="Chaos Roll", 
            ["recast_id"]=193, 
            ["type"]="CorsairRoll", 
            ["range"]=0, 
            ["icon_id"]=485, 
            ["element"]=1, 
            ["id"]=105, 
            ["duration"]=300, 
            ["mp_cost"]=0
        }
    }
}