return {
    ["rolls"]={
        [1]={
            ["ja"]="コルセアズロール", 
            ["prefix"]="/jobability", 
            ["icon_id"]=485, 
            ["range"]=0, 
            ["status"]=326, 
            ["tp_cost"]=0, 
            ["en"]="Corsair's Roll", 
            ["type"]="CorsairRoll", 
            ["targets"]={}, 
            ["recast_id"]=193, 
            ["element"]=1, 
            ["id"]=114, 
            ["duration"]=300, 
            ["mp_cost"]=0
        }, 
        [2]={
            ["ja"]="サムライロール", 
            ["prefix"]="/jobability", 
            ["icon_id"]=485, 
            ["range"]=0, 
            ["status"]=321, 
            ["tp_cost"]=0, 
            ["en"]="Samurai Roll", 
            ["type"]="CorsairRoll", 
            ["targets"]={}, 
            ["recast_id"]=193, 
            ["element"]=1, 
            ["id"]=109, 
            ["duration"]=300, 
            ["mp_cost"]=0
        }
    }, 
    ["layout"]={
        ["draggable"]=true, 
        ["padding"]=3, 
        ["font"]={
            ["name"]="Lucida Console", 
            ["size"]=9
        }, 
        ["colors"]={
            ["text"]={
                ["r"]=245, 
                ["alpha"]=255, 
                ["g"]=200, 
                ["b"]=20
            }, 
            ["bg"]={
                ["r"]=0, 
                ["alpha"]=200, 
                ["g"]=0, 
                ["b"]=0
            }, 
            ["stroke"]={
                ["r"]=0, 
                ["alpha"]=255, 
                ["g"]=0, 
                ["b"]=0
            }
        }, 
        ["stroke_width"]=1, 
        ["pos"]={
            ["y"]=800, 
            ["x"]=1200
        }
    }, 
    ["crooked"]=false, 
    ["important"]="25,165,200", 
    ["cap"]=7, 
    ["blink"]="110,235,50"
}